#!/usr/bin/env bash
# This script displays time from 00:01 to 12:59 using nested while loops.
hours=0
while [ "$hours" -le 12 ]; do
    minutes=1
    while [ "$minutes" -le 59 ]; do
        printf "%02d:%02d\n" "$hours" "$minutes"
        minutes=$((minutes + 1))
    done
    hours=$((hours + 1))
done | head -n 70

