#!/usr/bin/env bash
# Display PID and process name of processes containing "bash"
# shellcheck disable=SC2009
for pid in /proc/[0-9]*; do
    if [ -r "$pid/comm" ]; then
        name=$(<"$pid/comm")
        if [[ "$name" == *bash* ]]; then
            echo "$(basename "$pid") $name"
        fi
    fi
done
