#!/usr/bin/env bash
# This script automatically stops the 4-to_infinity_and_beyond process without using kill
# shellcheck disable=SC2009

for job in $(jobs -p); do
  cmd=$(cat /proc/"$job"/cmdline 2>/dev/null | tr '\0' ' ')
  if [[ $cmd == *4-to_infinity_and_beyond* ]]; then
    disown "$job"
    echo "Stopped 4-to_infinity_and_beyond (PID: $job) by disowning it"
    break
  fi
done
