#!/usr/bin/env bash
# This script kills the 7-highlander process
# shellcheck disable=SC2009

pid=$(pgrep -f 7-highlander)

if [ -n "$pid" ]; then
  kill "$pid"
  echo "Killed 7-highlander process with PID $pid."
else
  echo "7-highlander process not found."
fi

